name: model-distillation
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core deep learning and NLP
  - pytorch>=2.0.0
  - torchvision>=0.14.0
  - transformers>=4.50.0
  - datasets>=4.0.0
  - tokenizers>=0.21.0
  - accelerate>=1.0.0

  # Scientific computing stack
  - numpy>=2.0.0
  - pandas>=2.0.0
  - scipy>=1.7.0
  - scikit-learn>=0.24.0

  # Data processing
  - pyarrow>=21.0.0
  - dill>=0.3.8

  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.12.0

  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipython>=7.20.0
  - notebook>=6.3.0

  # Utilities
  - tqdm>=4.60.0
  - requests>=2.30.0
  - beautifulsoup4>=4.9.0
  - lxml>=4.6.0
  - click>=8.0.0

  # Development tools
  - pytest>=6.0.0
  - black>=22.0.0
  - flake8>=4.0.0

  # Pip-only packages
  - pip
  - pip:
    - safetensors>=0.5.0
    - multiprocess>=0.70.0
    - xxhash>=3.0.0
    - fsspec>=2025.1.0
    # Uncomment if needed:
    # - wandb>=0.15.0
    # - spacy>=3.4.0
    # - fastapi>=0.100.0
    # - uvicorn>=0.20.0